name: Feature request
description: Suggest a new idea for the extension
title: "[Feature request] "
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What is your feature request?
    validations:
      required: true
